type Country = {
  name: string;
  arName: string;
  code: string;
  dial_code: string;
};

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", arName: "أفغانستان", code: "AF", dial_code: "+93" },
  { name: "Albania", arName: "ألبانيا", code: "AL", dial_code: "+355" },
  { name: "Algeria", arName: "الجزائر", code: "DZ", dial_code: "+213" },
  { name: "Andorra", arName: "أندورا", code: "AD", dial_code: "+376" },
  { name: "Angola", arName: "أنغولا", code: "AO", dial_code: "+244" },
  { name: "Argentina", arName: "الأرجنتين", code: "AR", dial_code: "+54" },
  { name: "Armenia", arName: "أرمينيا", code: "AM", dial_code: "+374" },
  { name: "Australia", arName: "أستراليا", code: "AU", dial_code: "+61" },
  { name: "Austria", arName: "النمسا", code: "AT", dial_code: "+43" },
  { name: "Bahrain", arName: "البحرين", code: "BH", dial_code: "+973" },
  { name: "Bangladesh", arName: "بنغلاديش", code: "BD", dial_code: "+880" },
  { name: "Belgium", arName: "بلجيكا", code: "BE", dial_code: "+32" },
  { name: "Bolivia", arName: "بوليفيا", code: "BO", dial_code: "+591" },
  {
    name: "Bosnia and Herzegovina",
    arName: "البوسنة والهرسك",
    code: "BA",
    dial_code: "+387",
  },
  { name: "Brazil", arName: "البرازيل", code: "BR", dial_code: "+55" },
  { name: "Bulgaria", arName: "بلغاريا", code: "BG", dial_code: "+359" },
  { name: "Canada", arName: "كندا", code: "CA", dial_code: "+1" },
  { name: "Chile", arName: "تشيلي", code: "CL", dial_code: "+56" },
  { name: "China", arName: "الصين", code: "CN", dial_code: "+86" },
  { name: "Colombia", arName: "كولومبيا", code: "CO", dial_code: "+57" },
  { name: "Croatia", arName: "كرواتيا", code: "HR", dial_code: "+385" },
  {
    name: "Czech Republic",
    arName: "جمهورية التشيك",
    code: "CZ",
    dial_code: "+420",
  },
  { name: "Denmark", arName: "الدنمارك", code: "DK", dial_code: "+45" },
  { name: "Ecuador", arName: "الإكوادور", code: "EC", dial_code: "+593" },
  { name: "Egypt", arName: "مصر", code: "EG", dial_code: "+20" },
  { name: "El Salvador", arName: "السلفادور", code: "SV", dial_code: "+503" },
  { name: "Estonia", arName: "إستونيا", code: "EE", dial_code: "+372" },
  { name: "Finland", arName: "فنلندا", code: "FI", dial_code: "+358" },
  { name: "France", arName: "فرنسا", code: "FR", dial_code: "+33" },
  { name: "Germany", arName: "ألمانيا", code: "DE", dial_code: "+49" },
  { name: "Greece", arName: "اليونان", code: "GR", dial_code: "+30" },
  { name: "Guatemala", arName: "غواتيمالا", code: "GT", dial_code: "+502" },
  { name: "Honduras", arName: "هندوراس", code: "HN", dial_code: "+504" },
  { name: "Hong Kong", arName: "هونغ كونغ", code: "HK", dial_code: "+852" },
  { name: "Hungary", arName: "المجر", code: "HU", dial_code: "+36" },
  { name: "Iceland", arName: "آيسلندا", code: "IS", dial_code: "+354" },
  { name: "India", arName: "الهند", code: "IN", dial_code: "+91" },
  { name: "Indonesia", arName: "إندونيسيا", code: "ID", dial_code: "+62" },
  { name: "Iraq", arName: "العراق", code: "IQ", dial_code: "+964" },
  { name: "Ireland", arName: "أيرلندا", code: "IE", dial_code: "+353" },
  { name: "Israel", arName: "إسرائيل", code: "IL", dial_code: "+972" },
  { name: "Italy", arName: "إيطاليا", code: "IT", dial_code: "+39" },
  { name: "Japan", arName: "اليابان", code: "JP", dial_code: "+81" },
  { name: "Jordan", arName: "الأردن", code: "JO", dial_code: "+962" },
  { name: "Kazakhstan", arName: "كازاخستان", code: "KZ", dial_code: "+7" },
  { name: "Kenya", arName: "كينيا", code: "KE", dial_code: "+254" },
  { name: "Kuwait", arName: "الكويت", code: "KW", dial_code: "+965" },
  { name: "Lebanon", arName: "لبنان", code: "LB", dial_code: "+961" },
  { name: "Libya", arName: "ليبيا", code: "LY", dial_code: "+218" },
  { name: "Lithuania", arName: "ليتوانيا", code: "LT", dial_code: "+370" },
  { name: "Malaysia", arName: "ماليزيا", code: "MY", dial_code: "+60" },
  { name: "Mexico", arName: "المكسيك", code: "MX", dial_code: "+52" },
  { name: "Mongolia", arName: "منغوليا", code: "MN", dial_code: "+976" },
  { name: "Montenegro", arName: "الجبل الأسود", code: "ME", dial_code: "+382" },
  { name: "Morocco", arName: "المغرب", code: "MA", dial_code: "+212" },
  { name: "Nepal", arName: "نيبال", code: "NP", dial_code: "+977" },
  { name: "Netherlands", arName: "هولندا", code: "NL", dial_code: "+31" },
  { name: "New Zealand", arName: "نيوزيلندا", code: "NZ", dial_code: "+64" },
  { name: "Nicaragua", arName: "نيكاراغوا", code: "NI", dial_code: "+505" },
  { name: "Nigeria", arName: "نيجيريا", code: "NG", dial_code: "+234" },
  { name: "Norway", arName: "النرويج", code: "NO", dial_code: "+47" },
  { name: "Oman", arName: "عمان", code: "OM", dial_code: "+968" },
  { name: "Pakistan", arName: "باكستان", code: "PK", dial_code: "+92" },
  { name: "Palestine", arName: "فلسطين", code: "PS", dial_code: "+970" },
  { name: "Panama", arName: "بنما", code: "PA", dial_code: "+507" },
  { name: "Paraguay", arName: "باراغواي", code: "PY", dial_code: "+595" },
  { name: "Peru", arName: "بيرو", code: "PE", dial_code: "+51" },
  { name: "Philippines", arName: "الفلبين", code: "PH", dial_code: "+63" },
  { name: "Poland", arName: "بولندا", code: "PL", dial_code: "+48" },
  { name: "Portugal", arName: "البرتغال", code: "PT", dial_code: "+351" },
  { name: "Qatar", arName: "قطر", code: "QA", dial_code: "+974" },
  { name: "Romania", arName: "رومانيا", code: "RO", dial_code: "+40" },
  { name: "Russia", arName: "روسيا", code: "RU", dial_code: "+7" },
  {
    name: "Saudi Arabia",
    arName: "المملكة العربية السعودية",
    code: "SA",
    dial_code: "+966",
  },
  { name: "Serbia", arName: "صربيا", code: "RS", dial_code: "+381" },
  { name: "Singapore", arName: "سنغافورة", code: "SG", dial_code: "+65" },
  { name: "Slovakia", arName: "سلوفاكيا", code: "SK", dial_code: "+421" },
  { name: "Slovenia", arName: "سلوفينيا", code: "SI", dial_code: "+386" },
  { name: "South Africa", arName: "جنوب أفريقيا", code: "ZA", dial_code: "+27" },
  { name: "South Korea", arName: "كوريا الجنوبية", code: "KR", dial_code: "+82" },
  { name: "Spain", arName: "إسبانيا", code: "ES", dial_code: "+34" },
  { name: "Sri Lanka", arName: "سريلانكا", code: "LK", dial_code: "+94" },
  { name: "Sudan", arName: "السودان", code: "SD", dial_code: "+249" },
  { name: "Sweden", arName: "السويد", code: "SE", dial_code: "+46" },
  { name: "Switzerland", arName: "سويسرا", code: "CH", dial_code: "+41" },
  { name: "Syria", arName: "سوريا", code: "SY", dial_code: "+963" },
  { name: "Taiwan", arName: "تايوان", code: "TW", dial_code: "+886" },
  { name: "Thailand", arName: "تايلاند", code: "TH", dial_code: "+66" },
  { name: "Tunisia", arName: "تونس", code: "TN", dial_code: "+216" },
  { name: "Turkey", arName: "تركيا", code: "TR", dial_code: "+90" },
  { name: "Ukraine", arName: "أوكرانيا", code: "UA", dial_code: "+380" },
  {
    name: "United Arab Emirates",
    arName: "الإمارات العربية المتحدة",
    code: "AE",
    dial_code: "+971",
  },
  {
    name: "United Kingdom",
    arName: "المملكة المتحدة",
    code: "GB",
    dial_code: "+44",
  },
  {
    name: "United States",
    arName: "الولايات المتحدة",
    code: "US",
    dial_code: "+1",
  },
  { name: "Uruguay", arName: "الأوروغواي", code: "UY", dial_code: "+598" },
  { name: "Venezuela", arName: "فنزويلا", code: "VE", dial_code: "+58" },
  { name: "Vietnam", arName: "فيتنام", code: "VN", dial_code: "+84" },
  { name: "Yemen", arName: "اليمن", code: "YE", dial_code: "+967" },
];

export const getFlagEmoji = (countryCode: string) => {
  const codePoints = countryCode
    .toUpperCase()
    .split("")
    .map((char) => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
};
